#!/bin/zsh

# Master script to reset the shellx Zsh setup.
# 1. Regenerates the sourcing block for .zshrc
# 2. Regenerates completions based on aliases/functions
# 3. Resets ~/.zshrc to the minimal loader structure

setopt errexit
setopt pipefail

local shellx_dir="${HOME}/.shellx"
local zshrc_file="${HOME}/.zshrc"
local backup_file="${zshrc_file}_backup_$(date +%Y%m%d_%H%M%S)"

echo "Starting full shellx setup reset..."

# --- Step 1: Regenerate RC Sourcing ---
echo "\n--- Running generate_rc_sourcing.sh ---"
if [[ -x "${shellx_dir}/generate_rc_sourcing.sh" ]]; then
  # Run in a subshell to avoid potential variable conflicts if sourced
  ( "${shellx_dir}/generate_rc_sourcing.sh" )
else
  echo "Error: ${shellx_dir}/generate_rc_sourcing.sh not found or not executable." >&2
  exit 1
fi

# --- Step 2: Regenerate Completions ---
echo "\n--- Running generate_completions.sh ---"
if [[ -x "${shellx_dir}/generate_completions.sh" ]]; then
  # Run in a subshell
  ( "${shellx_dir}/generate_completions.sh" )
else
  echo "Error: ${shellx_dir}/generate_completions.sh not found or not executable." >&2
  exit 1
fi

# --- Step 3: Reset ~/.zshrc ---
echo "\n--- Resetting ${zshrc_file} ---"

# Backup existing file
if [[ -f "$zshrc_file" ]]; then
  echo "Backing up current ${zshrc_file} to ${backup_file}"
  cp "$zshrc_file" "$backup_file" || {
    echo "Error: Failed to create backup. Aborting reset of .zshrc." >&2
    exit 1
  }
fi

# Define the minimal content (same as in reset_zshrc function)
local minimal_content
minimal_content=$(cat <<-EOF
#!/bin/zsh

# ==== Source Modular Configuration Files ====
# Sources the block generated by ~/.shellx/generate_rc_sourcing.sh

# Use correct variable expansion within the heredoc for the final file
_generated_sourcing_file="\${HOME}/.shellx/generated_rc_sourcing.zsh"
if [[ -f "\$_generated_sourcing_file" ]]; then
  source "\$_generated_sourcing_file"
else
  # Fallback or error message if generator hasn't run?
  echo "Warning: Could not find generated sourcing file: \$_generated_sourcing_file" >&2
  echo "Your Zsh environment might be incomplete. Run ~/.shellx/generate_rc_sourcing.sh" >&2
  : # No-op
fi
unset _generated_sourcing_file

EOF
)

# Write the minimal content to .zshrc
echo "Generating new minimal ${zshrc_file}..."
# Use printf for potentially better handling than echo with variables
printf '%s' "$minimal_content" > "$zshrc_file" || {
  echo "Error: Failed to write to ${zshrc_file}. Check permissions." >&2
  exit 1
}

echo "Successfully reset ${zshrc_file}."

# --- Optional: Reset Antigen Cache ---
echo "\n--- Checking Antigen cache ---"
antigen_cache_dir="${HOME}/.antigen/bundles/robbyrussell/oh-my-zsh/cache"
if [[ -d "$antigen_cache_dir" ]]; then
  echo "Ensuring antigen cache directories exist..."
  mkdir -p "${antigen_cache_dir}/completions"
  echo "You may want to run 'rm -f ~/.antigen/.zcompdump*' if completion issues persist."
fi

echo "\nFull shellx setup reset completed."
echo "Please start a new shell session or run 'source ~/.zshrc' for changes to take effect."

exit 0